-- Seed Events Table with realistic event data
INSERT INTO events (event_id, name, event_date, location, status, guest_count, budget, manager_name, customer_name, customer_email, customer_phone, notes, event_type, venue_name, created_by) VALUES
('EVT-001', 'Emma & Liam''s Wedding', '2025-08-20', 'Seaside Cliffs Resort, Malibu, California', 'confirmed', 150, 4500000, 'Maya Brooks', 'Emma Thompson', 'emma.thompson@example.com', '(555) 123-4567', 'Garden ceremony followed by beach reception. Bride wants gold and blush color scheme.', 'wedding', 'Seaside Cliffs Resort', 'admin'),
('EVT-002', 'TechStart Annual Gala', '2025-09-15', 'Grand Hyatt, San Francisco', 'planning', 300, 7500000, 'David Chen', 'Sarah Johnson', 'sarah.johnson@techstart.com', '(555) 234-5678', 'Corporate event with keynote speakers. Need AV setup for presentations.', 'corporate', 'Grand Hyatt', 'admin'),
('EVT-003', 'Sarah''s 30th Birthday', '2025-07-10', 'The Garden Room, Austin', 'completed', 50, 500000, 'Sarah Jones', 'Sarah Miller', 'sarah.miller@example.com', '(555) 345-6789', 'Intimate garden party with string lights and floral arrangements.', 'birthday', 'The Garden Room', 'admin'),
('EVT-004', 'Corporate Retreat 2025', '2025-10-05', 'Mountain View Lodge, Colorado', 'pending', 80, 2500000, 'Michael Brown', 'Robert Wilson', 'robert.wilson@corporation.com', '(555) 456-7890', 'Team building retreat with outdoor activities and workshops.', 'corporate', 'Mountain View Lodge', 'admin'),
('EVT-005', 'Jennifer & Mark''s Engagement Party', '2025-06-15', 'The Vineyard Estate, Napa Valley', 'confirmed', 75, 1250000, 'Emily Rodriguez', 'Jennifer Davis', 'jennifer.davis@example.com', '(555) 567-8901', 'Wine tasting theme with vineyard views. Family-style dinner setup.', 'engagement', 'The Vineyard Estate', 'admin'),
('EVT-006', 'Holiday Charity Ball', '2025-12-01', 'Royal Palace Hotel, New York', 'planning', 400, 10000000, 'James Wilson', 'Charity Foundation', 'info@charityfoundation.org', '(555) 678-9012', 'Black-tie charity event with silent auction and live band.', 'charity', 'Royal Palace Hotel', 'admin'),
('EVT-007', 'Anniversary Celebration', '2025-09-28', 'Belvedere Mansion, Beverly Hills', 'confirmed', 120, 3500000, 'Lisa Thompson', 'Margaret & Thomas Anderson', 'margaret.anderson@example.com', '(555) 789-0123', '25th wedding anniversary with cocktail hour and plated dinner.', 'anniversary', 'Belvedere Mansion', 'admin'),
('EVT-008', 'Product Launch Event', '2025-11-12', 'Innovation Center, Seattle', 'planning', 200, 6000000, 'Kevin Park', 'InnovateLabs Inc.', 'events@innovatelabs.com', '(555) 890-1234', 'Tech product launch with demos, networking, and catering.', 'corporate', 'Innovation Center', 'admin'),
('EVT-009', 'Baby Shower Extravaganza', '2025-08-03', 'Rose Garden Pavilion, Pasadena', 'confirmed', 60, 800000, 'Amanda White', 'Rachel Green', 'rachel.green@example.com', '(555) 901-2345', 'Garden-themed baby shower with games and elegant decor.', 'baby_shower', 'Rose Garden Pavilion', 'admin'),
('EVT-010', 'Art Gallery Opening', '2025-10-18', 'Modern Art Gallery, Los Angeles', 'pending', 150, 2000000, 'Christopher Lee', 'Artistic Visions Gallery', 'info@artisticvisions.com', '(555) 012-3456', 'Contemporary art exhibition opening with champagne reception.', 'art_exhibition', 'Modern Art Gallery', 'admin'),
('EVT-011', 'Retirement Celebration', '2025-07-25', 'Lakeview Country Club, Chicago', 'confirmed', 100, 1500000, 'Patricia Moore', 'John Retirement Fund', 'john.doe@example.com', '(555) 123-4567', 'Outdoor celebration with golf cart parade and farewell speeches.', 'retirement', 'Lakeview Country Club', 'admin'),
('EVT-012', 'Fashion Show After-Party', '2025-09-30', 'Skyline Rooftop, Miami', 'planning', 250, 5500000, 'Daniel Garcia', 'Elite Fashion Magazine', 'events@elitefashion.com', '(555) 234-5678', 'Exclusive after-party for fashion industry VIPs with DJ and open bar.', 'fashion', 'Skyline Rooftop', 'admin')
ON CONFLICT (event_id) DO NOTHING;
